//! The set of roundtrip cases exercised against embedded Postgres.
//!
//! Cases come from two places: the generated `tests/testdata/*.arrow` files (see
//! `tests/generate_test_data.py`) and hand written cases built with the Arrow builders below.
//! Both are described by the same [`Case`] struct so a future property based test can generate
//! [`Case`]s and reuse the same assertion machinery.

use std::collections::HashMap;
use std::fs::File;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use arrow::buffer::{NullBuffer, OffsetBuffer};
use arrow_array::builder::{ListBuilder, StringBuilder};
use arrow_array::{
    ArrayRef, BooleanArray, Float64Array, Int32Array, ListArray, RecordBatch, StringArray,
    StructArray,
};
use arrow_ipc::reader::FileReader;
use arrow_schema::{DataType, Field, Fields, Schema};
use pgpq::encoders::{EncoderBuilder, ListEncoderBuilder, StringEncoderBuilder};
use pgpq::pg_schema::PostgresType;

use super::value::{expected_rows, Value};

/// One roundtrip case: some Arrow data, optionally custom encoders, and the values Postgres is
/// expected to hand back.
///
/// `Debug` is required by `proptest`, which prints the generated (and shrunk) case on failure.
#[derive(Debug)]
pub struct Case {
    pub name: String,
    pub schema: Schema,
    pub batches: Vec<RecordBatch>,
    /// Custom encoder builders keyed by field name, as in
    /// [`pgpq::ArrowToPostgresBinaryEncoder::try_new_with_encoders`].
    pub encoders: Option<HashMap<String, EncoderBuilder>>,
    /// Overrides the expectation derived from the Arrow data. Needed when the Postgres type does
    /// not roundtrip byte for byte, e.g. `JSONB` normalizes whitespace.
    pub expected_override: Option<Vec<Vec<Value>>>,
}

impl Case {
    pub fn new(name: impl Into<String>, batch: RecordBatch) -> Case {
        Case {
            name: name.into(),
            schema: (*batch.schema()).clone(),
            batches: vec![batch],
            encoders: None,
            expected_override: None,
        }
    }

    pub fn with_encoders(mut self, encoders: HashMap<String, EncoderBuilder>) -> Case {
        self.encoders = Some(encoders);
        self
    }

    pub fn with_expected(mut self, expected: Vec<Vec<Value>>) -> Case {
        self.expected_override = Some(expected);
        self
    }

    /// The values Postgres should return, row major.
    pub fn expected(&self) -> Vec<Vec<Value>> {
        self.expected_override
            .clone()
            .unwrap_or_else(|| expected_rows(&self.batches))
    }
}

pub fn read_batches(file: &Path) -> (Vec<RecordBatch>, Schema) {
    let file = File::open(file).unwrap();
    let reader = FileReader::try_new(file, None).unwrap();
    let schema = (*reader.schema()).clone();
    let batches = reader.map(|v| v.unwrap()).collect();
    (batches, schema)
}

pub fn testdata_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/testdata")
}

/// Every case generated by `tests/generate_test_data.py`, in a stable order.
pub fn testdata_cases() -> Vec<Case> {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(testdata_dir())
        .unwrap()
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|s| s.to_str()) == Some("arrow"))
        .collect();
    paths.sort();
    paths
        .into_iter()
        .map(|path| {
            let name = path.file_stem().unwrap().to_str().unwrap().to_owned();
            let (batches, schema) = read_batches(&path);
            Case {
                name,
                schema,
                batches,
                encoders: None,
                expected_override: None,
            }
        })
        .collect()
}

fn single_column_batch(field: Field, array: ArrayRef) -> RecordBatch {
    let schema = Arc::new(Schema::new(vec![field]));
    RecordBatch::try_new(schema, vec![array]).unwrap()
}

fn num_text_fields() -> Fields {
    Fields::from(vec![
        Field::new("num", DataType::Int32, true),
        Field::new("text", DataType::Utf8, true),
    ])
}

/// Struct (Postgres composite type) cases, ported from the Python `test_struct.py` suite.
pub fn struct_cases() -> Vec<Case> {
    let mut cases = Vec::new();

    // A basic struct of an int and a string.
    {
        let fields = num_text_fields();
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int32Array::from(vec![1, 2, 3])),
            Arc::new(StringArray::from(vec!["a", "b", "c"])),
        ];
        let array = Arc::new(StructArray::new(fields.clone(), columns, None)) as ArrayRef;
        cases.push(Case::new(
            "basic_struct",
            single_column_batch(
                Field::new("my_struct", DataType::Struct(fields), false),
                array,
            ),
        ));
    }

    // A nullable struct column where one whole struct is null.
    {
        let fields = num_text_fields();
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int32Array::from(vec![Some(1), None, Some(3)])),
            Arc::new(StringArray::from(vec![Some("a"), None, Some("c")])),
        ];
        let nulls = NullBuffer::from(vec![true, false, true]);
        let array = Arc::new(StructArray::new(fields.clone(), columns, Some(nulls))) as ArrayRef;
        cases.push(Case::new(
            "nullable_struct",
            single_column_batch(
                Field::new("my_struct", DataType::Struct(fields), true),
                array,
            ),
        ));
    }

    // A non-null struct that has null *field* values, which is a different code path from a null
    // struct.
    {
        let fields = num_text_fields();
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int32Array::from(vec![Some(1), None, None])),
            Arc::new(StringArray::from(vec![None, Some("b"), None])),
        ];
        let array = Arc::new(StructArray::new(fields.clone(), columns, None)) as ArrayRef;
        cases.push(Case::new(
            "struct_with_null_fields",
            single_column_batch(
                Field::new("my_struct", DataType::Struct(fields), false),
                array,
            ),
        ));
    }

    // A struct mixing int, float and bool fields.
    {
        let fields = Fields::from(vec![
            Field::new("int_field", DataType::Int32, true),
            Field::new("float_field", DataType::Float64, true),
            Field::new("bool_field", DataType::Boolean, true),
        ]);
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int32Array::from(vec![1, 2])),
            Arc::new(Float64Array::from(vec![1.5, 2.5])),
            Arc::new(BooleanArray::from(vec![true, false])),
        ];
        let array = Arc::new(StructArray::new(fields.clone(), columns, None)) as ArrayRef;
        cases.push(Case::new(
            "struct_with_mixed_fields",
            single_column_batch(
                Field::new("complex_struct", DataType::Struct(fields), false),
                array,
            ),
        ));
    }

    // NOTE: a struct with a *list* field is not covered because `StructEncoderBuilder` requires
    // every field type to have an OID and `PostgresType::List` has none, so building the encoder
    // panics. See the note in `core/src/encoders.rs` (`StructEncoderBuilder::try_new`).

    // An array of structs (`composite_type[]`), with more than one struct per row.
    {
        let fields = num_text_fields();
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int32Array::from(vec![1, 2, 3, 4])),
            Arc::new(StringArray::from(vec!["a", "b", "c", "d"])),
        ];
        let structs = Arc::new(StructArray::new(fields.clone(), columns, None)) as ArrayRef;
        let item = Arc::new(Field::new("item", DataType::Struct(fields), true));
        let offsets = OffsetBuffer::new(vec![0, 3, 4].into());
        let list = Arc::new(ListArray::new(item.clone(), offsets, structs, None)) as ArrayRef;
        cases.push(Case::new(
            "array_of_structs",
            single_column_batch(
                Field::new("struct_array", DataType::List(item), false),
                list,
            ),
        ));
    }

    cases
}

/// Cases that override the default encoder selection, e.g. writing Arrow strings as `JSONB`.
pub fn custom_encoder_cases() -> Vec<Case> {
    let mut builder = ListBuilder::new(StringBuilder::new()).with_field(Arc::new(Field::new(
        "field",
        DataType::Utf8,
        true,
    )));
    builder.append_value([Some("[]")]);
    builder.append_value([Some("{\"foo\":\"bar\"}")]);
    builder.append_value([Some("123")]);
    let list = Arc::new(builder.finish()) as ArrayRef;
    let field = Field::new_list("json_list", Field::new("field", DataType::Utf8, true), true);
    let batch = single_column_batch(field.clone(), list);

    let inner = Field::new("field", DataType::Utf8, true);
    let encoder = ListEncoderBuilder::new_with_inner(
        Arc::new(field),
        EncoderBuilder::String(
            StringEncoderBuilder::new_with_output(Arc::new(inner), PostgresType::Jsonb).unwrap(),
        ),
    )
    .unwrap();
    let encoders = HashMap::from([("json_list".to_string(), EncoderBuilder::List(encoder))]);

    // JSONB is a parsed representation, so Postgres hands back canonical JSON text rather than the
    // exact input bytes.
    let expected = vec![
        vec![Value::Array(vec![Value::Text("[]".into())])],
        vec![Value::Array(vec![Value::Text("{\"foo\": \"bar\"}".into())])],
        vec![Value::Array(vec![Value::Text("123".into())])],
    ];

    vec![Case::new("json_list", batch)
        .with_encoders(encoders)
        .with_expected(expected)]
}

/// Every case, in the order they should be run.
pub fn all_cases() -> Vec<Case> {
    let mut cases = testdata_cases();
    cases.extend(struct_cases());
    cases.extend(custom_encoder_cases());
    cases
}

/// Sanity check that a case actually produced rows; guards against a silently empty sweep.
pub fn total_rows(cases: &[Case]) -> usize {
    cases
        .iter()
        .flat_map(|case| case.batches.iter())
        .map(|batch| batch.num_rows())
        .sum()
}
