name: Python arrow-json CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arrow-json:
    uses: ./.github/workflows/python-package.yaml
    with:
      package_name: arrow-json
      package_dir: json
    secrets: inherit
