name: Python pgpq CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pgpq:
    uses: ./.github/workflows/python-package.yaml
    with:
      package_name: pgpq
      package_dir: py
      import_name: pgpq
    secrets: inherit
